namespace Dotori.Core.Grammar;

/// <summary>Emacs Lisp (.el) 문법 파일 생성기.</summary>
/// <remarks>Emacs의 font-lock-keywords를 사용한 주요 색상 강조를 제공합니다.</remarks>
public sealed class EmacsGenerator : IGrammarGenerator
{
    public string FormatId => "emacs";
    public string DefaultExtension => ".el";

    private const string Template = """
        ;;; dotori-mode.el --- Major mode for Dotori build system files  -*- lexical-binding: t; -*-
        ;;; Generated by `dotori export grammar --format emacs`
        ;;
        ;; Usage:
        ;;   (load "~/.emacs.d/dotori-mode.el")
        ;;   .dotori 파일을 열면 자동으로 활성화됩니다.

        (defvar dotori-top-keywords
          '({{TOP_KEYWORDS}})
          "Dotori top-level declaration keywords.")

        (defvar dotori-block-keywords
          '({{BLOCK_KEYWORDS}})
          "Dotori block-opening keywords.")

        (defvar dotori-property-keywords
          '({{PROPERTY_KEYWORDS}})
          "Dotori property keywords.")

        (defvar dotori-type-values
          '({{TYPE_VALUES}})
          "Dotori project type values.")

        (defvar dotori-enum-values
          '({{ENUM_VALUES}})
          "Dotori enum/constant values.")

        (defvar dotori-condition-atoms
          '({{CONDITION_ATOMS}})
          "Dotori condition block atoms.")

        (defun dotori--keywords-regexp (words)
          "Build a regexp matching any word in WORDS as a whole word."
          (concat "\\b" (regexp-opt words t) "\\b"))

        (defvar dotori-font-lock-keywords
          (list
            ;; Line comments (# and //)
            '("\\(#\\|//\\).*$" . font-lock-comment-face)
            ;; Block comments (* ... *)
            '("(\\*" . font-lock-comment-face)
            ;; ${VAR} environment variable interpolation inside strings
            '("\\${[^}]*}" . font-lock-variable-name-face)
            ;; Top-level keywords
            (list (dotori--keywords-regexp dotori-top-keywords) 1 'font-lock-keyword-face)
            ;; Block keywords
            (list (dotori--keywords-regexp dotori-block-keywords) 1 'font-lock-builtin-face)
            ;; Property keywords
            (list (dotori--keywords-regexp dotori-property-keywords) 1 'font-lock-type-face)
            ;; C++ std values (c++17, c++20, c++23)
            '("\\b\\(c\\+\\+17\\|c\\+\\+20\\|c\\+\\+23\\)\\b" . font-lock-constant-face)
            ;; Type values
            (list (dotori--keywords-regexp dotori-type-values) 1 'font-lock-type-face)
            ;; Enum/constant values
            (list (dotori--keywords-regexp dotori-enum-values) 1 'font-lock-constant-face)
            ;; Condition block atoms  [ ... ]
            (list (dotori--keywords-regexp dotori-condition-atoms) 1 'font-lock-preprocessor-face)
            ;; Numbers
            '("\\b[0-9]+\\b" . font-lock-constant-face))
          "Font-lock keywords for dotori-mode.")

        (defvar dotori-mode-syntax-table
          (let ((table (make-syntax-table)))
            ;; # 줄 주석
            (modify-syntax-entry ?# "<" table)
            (modify-syntax-entry ?\n ">" table)
            ;; 문자열
            (modify-syntax-entry ?\" "\"" table)
            ;; 블록 구분자
            (modify-syntax-entry ?{ "(}" table)
            (modify-syntax-entry ?} "){" table)
            (modify-syntax-entry ?[ "(]" table)
            (modify-syntax-entry ?] ")[" table)
            ;; 하이픈을 단어 문자로 취급 (compile-flags 등)
            (modify-syntax-entry ?- "w" table)
            table)
          "Syntax table for dotori-mode.")

        ;;;###autoload
        (define-derived-mode dotori-mode prog-mode "Dotori"
          "Major mode for editing Dotori build system files (.dotori)."
          :syntax-table dotori-mode-syntax-table
          (setq-local font-lock-defaults '(dotori-font-lock-keywords))
          (setq-local comment-start "# ")
          (setq-local comment-end "")
          (setq-local indent-tabs-mode nil)
          (setq-local tab-width 4))

        ;;;###autoload
        (add-to-list 'auto-mode-alist '("\\.dotori\\'" . dotori-mode))

        (provide 'dotori-mode)
        ;;; dotori-mode.el ends here
        """;

    public string Generate()
    {
        var allConds = DotoriGrammarDefinition.PlatformConditions
            .Concat(DotoriGrammarDefinition.ConfigConditions)
            .Concat(DotoriGrammarDefinition.CompilerConditions)
            .Concat(DotoriGrammarDefinition.RuntimeConditions)
            .Distinct();

        var vars = new Dictionary<string, string>
        {
            ["TOP_KEYWORDS"]      = EmacsQuoted(DotoriGrammarDefinition.TopLevelKeywords),
            ["BLOCK_KEYWORDS"]    = EmacsQuoted(DotoriGrammarDefinition.BlockKeywords),
            ["PROPERTY_KEYWORDS"] = EmacsQuoted(DotoriGrammarDefinition.PropertyKeywords),
            ["TYPE_VALUES"]       = EmacsQuoted(DotoriGrammarDefinition.TypeValues),
            ["ENUM_VALUES"]       = EmacsQuoted(DotoriGrammarDefinition.EnumValues),
            ["CONDITION_ATOMS"]   = EmacsQuoted(allConds),
        };
        return TemplateEngine.Render(Template, vars);
    }

    private static string EmacsQuoted(IEnumerable<string> keywords) =>
        string.Join(" ", keywords.Select(k => $"\"{k}\""));
}
