using System.Text;

namespace Dotori.Core.Grammar;

/// <summary>Emacs Lisp (.el) 문법 파일 생성기.</summary>
/// <remarks>Emacs의 font-lock-keywords를 사용한 주요 색상 강조를 제공합니다.</remarks>
public sealed class EmacsGenerator : IGrammarGenerator
{
    public string FormatId => "emacs";
    public string DefaultExtension => ".el";

    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine(";;; dotori-mode.el --- Major mode for Dotori build system files  -*- lexical-binding: t; -*-");
        sb.AppendLine(";;; Generated by `dotori export grammar --format emacs`");
        sb.AppendLine(";;");
        sb.AppendLine(";; Usage:");
        sb.AppendLine(";;   (load \"~/.emacs.d/dotori-mode.el\")");
        sb.AppendLine(";;   dotori 파일을 열면 자동으로 활성화됩니다.");
        sb.AppendLine();

        // 키워드 목록 변수 정의
        sb.AppendLine("(defvar dotori-top-keywords");
        sb.AppendLine($"  '({EmacsSymbolList(DotoriGrammarDefinition.TopLevelKeywords)})");
        sb.AppendLine("  \"Dotori top-level declaration keywords.\")");
        sb.AppendLine();

        sb.AppendLine("(defvar dotori-block-keywords");
        sb.AppendLine($"  '({EmacsSymbolList(DotoriGrammarDefinition.BlockKeywords)})");
        sb.AppendLine("  \"Dotori block-opening keywords.\")");
        sb.AppendLine();

        sb.AppendLine("(defvar dotori-property-keywords");
        sb.AppendLine($"  '({EmacsSymbolList(DotoriGrammarDefinition.PropertyKeywords)})");
        sb.AppendLine("  \"Dotori property keywords.\")");
        sb.AppendLine();

        sb.AppendLine("(defvar dotori-type-values");
        sb.AppendLine($"  '({EmacsSymbolList(DotoriGrammarDefinition.TypeValues)})");
        sb.AppendLine("  \"Dotori project type values.\")");
        sb.AppendLine();

        sb.AppendLine("(defvar dotori-enum-values");
        sb.AppendLine($"  '({EmacsSymbolList(DotoriGrammarDefinition.EnumValues)})");
        sb.AppendLine("  \"Dotori enum/constant values.\")");
        sb.AppendLine();

        sb.AppendLine("(defvar dotori-condition-atoms");
        var allConditions = DotoriGrammarDefinition.PlatformConditions
            .Concat(DotoriGrammarDefinition.ConfigConditions)
            .Concat(DotoriGrammarDefinition.CompilerConditions)
            .Concat(DotoriGrammarDefinition.RuntimeConditions)
            .Distinct();
        sb.AppendLine($"  '({EmacsSymbolList(allConditions)})");
        sb.AppendLine("  \"Dotori condition block atoms.\")");
        sb.AppendLine();

        // 정규식 헬퍼
        sb.AppendLine("(defun dotori--keywords-regexp (words)");
        sb.AppendLine("  \"Build a regexp matching any word in WORDS as a whole word.\"");
        sb.AppendLine("  (concat \"\\\\b\" (regexp-opt words t) \"\\\\b\"))");
        sb.AppendLine();

        // font-lock 키워드 정의
        sb.AppendLine("(defvar dotori-font-lock-keywords");
        sb.AppendLine("  (list");
        sb.AppendLine("    ;; Line comments (# and //)");
        sb.AppendLine("    '(\"\\\\(#\\\\|//\\\\).*$\" . font-lock-comment-face)");
        sb.AppendLine("    ;; Block comments (* ... *)");
        sb.AppendLine("    '(\"(\\\\*\" . font-lock-comment-face)");
        sb.AppendLine("    ;; ${VAR} environment variable interpolation inside strings");
        sb.AppendLine("    '(\"\\\\${[^}]*}\" . font-lock-variable-name-face)");
        sb.AppendLine("    ;; Top-level keywords");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-top-keywords) 1 'font-lock-keyword-face)");
        sb.AppendLine("    ;; Block keywords");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-block-keywords) 1 'font-lock-builtin-face)");
        sb.AppendLine("    ;; Property keywords");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-property-keywords) 1 'font-lock-type-face)");
        sb.AppendLine("    ;; C++ std values (c++17, c++20, c++23)");
        sb.AppendLine("    '(\"\\\\b\\\\(c\\\\+\\\\+17\\\\|c\\\\+\\\\+20\\\\|c\\\\+\\\\+23\\\\)\\\\b\" . font-lock-constant-face)");
        sb.AppendLine("    ;; Type values");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-type-values) 1 'font-lock-type-face)");
        sb.AppendLine("    ;; Enum/constant values");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-enum-values) 1 'font-lock-constant-face)");
        sb.AppendLine("    ;; Condition block atoms  [ ... ]");
        sb.AppendLine("    (list (dotori--keywords-regexp dotori-condition-atoms) 1 'font-lock-preprocessor-face)");
        sb.AppendLine("    ;; Numbers");
        sb.AppendLine("    '(\"\\\\b[0-9]+\\\\b\" . font-lock-constant-face))");
        sb.AppendLine("  \"Font-lock keywords for dotori-mode.\")");
        sb.AppendLine();

        // syntax table
        sb.AppendLine("(defvar dotori-mode-syntax-table");
        sb.AppendLine("  (let ((table (make-syntax-table)))");
        sb.AppendLine("    ;; # 줄 주석");
        sb.AppendLine("    (modify-syntax-entry ?# \"<\" table)");
        sb.AppendLine("    (modify-syntax-entry ?\\n \">\" table)");
        sb.AppendLine("    ;; 문자열");
        sb.AppendLine("    (modify-syntax-entry ?\" \"\\\"\" table)");
        sb.AppendLine("    ;; 블록 구분자");
        sb.AppendLine("    (modify-syntax-entry ?{ \"(}\" table)");
        sb.AppendLine("    (modify-syntax-entry ?} \"){\" table)");
        sb.AppendLine("    (modify-syntax-entry ?[ \"(]\" table)");
        sb.AppendLine("    (modify-syntax-entry ?] \")[\" table)");
        sb.AppendLine("    ;; 하이픈을 단어 문자로 취급 (compile-flags 등)");
        sb.AppendLine("    (modify-syntax-entry ?- \"w\" table)");
        sb.AppendLine("    table)");
        sb.AppendLine("  \"Syntax table for dotori-mode.\")");
        sb.AppendLine();

        // major mode 정의
        sb.AppendLine(";;;###autoload");
        sb.AppendLine("(define-derived-mode dotori-mode prog-mode \"Dotori\"");
        sb.AppendLine("  \"Major mode for editing Dotori build system files (.dotori).\"");
        sb.AppendLine("  :syntax-table dotori-mode-syntax-table");
        sb.AppendLine("  (setq-local font-lock-defaults '(dotori-font-lock-keywords))");
        sb.AppendLine("  (setq-local comment-start \"# \")");
        sb.AppendLine("  (setq-local comment-end \"\")");
        sb.AppendLine("  (setq-local indent-tabs-mode nil)");
        sb.AppendLine("  (setq-local tab-width 4))");
        sb.AppendLine();

        sb.AppendLine(";;;###autoload");
        sb.AppendLine("(add-to-list 'auto-mode-alist '(\"\\\\.dotori\\\\'\" . dotori-mode))");
        sb.AppendLine();

        sb.AppendLine("(provide 'dotori-mode)");
        sb.AppendLine(";;; dotori-mode.el ends here");

        return sb.ToString();
    }

    private static string EmacsSymbolList(IEnumerable<string> keywords) =>
        string.Join(" ", keywords.Select(k => $"\"{k}\""));
}
