using System.Text;

namespace Dotori.Core.Grammar;

/// <summary>Sublime Text .sublime-syntax (YAML) 파일 생성기.</summary>
/// <remarks>Sublime Text 3 이상에서 사용하는 현대적 문법 형식입니다.</remarks>
public sealed class SublimeSyntaxGenerator : IGrammarGenerator
{
    public string FormatId => "sublime";
    public string DefaultExtension => ".sublime-syntax";

    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("%YAML 1.2");
        sb.AppendLine("---");
        sb.AppendLine("# Sublime Text syntax definition for Dotori build system (.dotori)");
        sb.AppendLine("# Generated by `dotori export grammar --format sublime`");
        sb.AppendLine("name: Dotori");
        sb.AppendLine("file_extensions:");
        sb.AppendLine("  - dotori");
        sb.AppendLine("scope: source.dotori");
        sb.AppendLine();
        sb.AppendLine("contexts:");
        sb.AppendLine("  main:");
        sb.AppendLine("    - include: comments");
        sb.AppendLine("    - include: strings");
        sb.AppendLine("    - include: condition-blocks");
        sb.AppendLine("    - include: top-keywords");
        sb.AppendLine("    - include: block-keywords");
        sb.AppendLine("    - include: property-keywords");
        sb.AppendLine("    - include: value-keywords");
        sb.AppendLine("    - include: numbers");
        sb.AppendLine("    - include: operators");
        sb.AppendLine();

        // 주석
        sb.AppendLine("  comments:");
        sb.AppendLine("    - match: '#.*$'");
        sb.AppendLine("      scope: comment.line.number-sign.dotori");
        sb.AppendLine("    - match: '//.*$'");
        sb.AppendLine("      scope: comment.line.double-slash.dotori");
        sb.AppendLine("    - match: '\\(\\*'");
        sb.AppendLine("      scope: punctuation.definition.comment.dotori");
        sb.AppendLine("      push: block-comment");
        sb.AppendLine();
        sb.AppendLine("  block-comment:");
        sb.AppendLine("    - meta_scope: comment.block.dotori");
        sb.AppendLine("    - match: '\\*\\)'");
        sb.AppendLine("      scope: punctuation.definition.comment.dotori");
        sb.AppendLine("      pop: true");
        sb.AppendLine();

        // 문자열
        sb.AppendLine("  strings:");
        sb.AppendLine("    - match: '\"'");
        sb.AppendLine("      scope: punctuation.definition.string.begin.dotori");
        sb.AppendLine("      push: string-body");
        sb.AppendLine();
        sb.AppendLine("  string-body:");
        sb.AppendLine("    - meta_scope: string.quoted.double.dotori");
        sb.AppendLine("    - match: '\"'");
        sb.AppendLine("      scope: punctuation.definition.string.end.dotori");
        sb.AppendLine("      pop: true");
        sb.AppendLine("    - match: '\\$\\{[^}]*\\}'");
        sb.AppendLine("      scope: variable.other.env.dotori");
        sb.AppendLine("    - match: '\\\\.'");
        sb.AppendLine("      scope: constant.character.escape.dotori");
        sb.AppendLine();

        // 조건 블록
        sb.AppendLine("  condition-blocks:");
        sb.AppendLine("    - match: '\\['");
        sb.AppendLine("      scope: punctuation.section.condition.begin.dotori");
        sb.AppendLine("      push: condition-body");
        sb.AppendLine();
        sb.AppendLine("  condition-body:");
        sb.AppendLine("    - meta_scope: meta.condition.dotori");
        sb.AppendLine("    - match: '\\]'");
        sb.AppendLine("      scope: punctuation.section.condition.end.dotori");
        sb.AppendLine("      pop: true");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.PlatformConditions)})\\b'");
        sb.AppendLine("      scope: keyword.control.platform.dotori");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.ConfigConditions)})\\b'");
        sb.AppendLine("      scope: keyword.control.config.dotori");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.CompilerConditions)})\\b'");
        sb.AppendLine("      scope: keyword.control.compiler.dotori");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.RuntimeConditions)})\\b'");
        sb.AppendLine("      scope: keyword.control.runtime.dotori");
        sb.AppendLine("    - match: '\\.'");
        sb.AppendLine("      scope: punctuation.separator.condition.dotori");
        sb.AppendLine();

        // 최상위 키워드
        sb.AppendLine("  top-keywords:");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.TopLevelKeywords)})\\b'");
        sb.AppendLine("      scope: keyword.declaration.dotori");
        sb.AppendLine();

        // 블록 키워드
        sb.AppendLine("  block-keywords:");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.BlockKeywords)})\\b'");
        sb.AppendLine("      scope: keyword.other.block.dotori");
        sb.AppendLine();

        // 프로퍼티 키워드
        sb.AppendLine("  property-keywords:");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.PropertyKeywords)})\\b'");
        sb.AppendLine("      scope: support.type.property-name.dotori");
        sb.AppendLine();

        // 값 키워드
        sb.AppendLine("  value-keywords:");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.TypeValues)})\\b'");
        sb.AppendLine("      scope: support.constant.type.dotori");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.StdValues.Select(EscapeYamlRegex))})\\b'");
        sb.AppendLine("      scope: constant.language.std.dotori");
        sb.AppendLine($"    - match: '\\b({Alternation(DotoriGrammarDefinition.EnumValues.Select(EscapeYamlRegex))})\\b'");
        sb.AppendLine("      scope: constant.language.dotori");
        sb.AppendLine();

        // 숫자
        sb.AppendLine("  numbers:");
        sb.AppendLine("    - match: '\\b\\d+\\b'");
        sb.AppendLine("      scope: constant.numeric.integer.dotori");
        sb.AppendLine();

        // 연산자
        sb.AppendLine("  operators:");
        sb.AppendLine("    - match: '='");
        sb.AppendLine("      scope: keyword.operator.assignment.dotori");

        return sb.ToString();
    }

    private static string Alternation(IEnumerable<string> keywords) =>
        string.Join("|", keywords);

    private static string EscapeYamlRegex(string s) =>
        s.Replace("+", "\\+").Replace(".", "\\.");
}
