namespace Dotori.Core.Grammar;

/// <summary>Sublime Text .sublime-syntax (YAML) 파일 생성기.</summary>
/// <remarks>Sublime Text 3 이상에서 사용하는 현대적 문법 형식입니다.</remarks>
public sealed class SublimeSyntaxGenerator : IGrammarGenerator
{
    public string FormatId => "sublime";
    public string DefaultExtension => ".sublime-syntax";

    private const string Template = """
        %YAML 1.2
        ---
        # Sublime Text syntax definition for Dotori build system (.dotori)
        # Generated by `dotori export grammar --format sublime`
        name: Dotori
        file_extensions:
          - dotori
        scope: source.dotori

        contexts:
          main:
            - include: comments
            - include: strings
            - include: condition-blocks
            - include: top-keywords
            - include: block-keywords
            - include: property-keywords
            - include: value-keywords
            - include: numbers
            - include: operators

          comments:
            - match: '#.*$'
              scope: comment.line.number-sign.dotori
            - match: '//.*$'
              scope: comment.line.double-slash.dotori
            - match: '\(\*'
              scope: punctuation.definition.comment.dotori
              push: block-comment

          block-comment:
            - meta_scope: comment.block.dotori
            - match: '\*\)'
              scope: punctuation.definition.comment.dotori
              pop: true

          strings:
            - match: '"'
              scope: punctuation.definition.string.begin.dotori
              push: string-body

          string-body:
            - meta_scope: string.quoted.double.dotori
            - match: '"'
              scope: punctuation.definition.string.end.dotori
              pop: true
            - match: '\$\{[^}]*\}'
              scope: variable.other.env.dotori
            - match: '\\.'
              scope: constant.character.escape.dotori

          condition-blocks:
            - match: '\['
              scope: punctuation.section.condition.begin.dotori
              push: condition-body

          condition-body:
            - meta_scope: meta.condition.dotori
            - match: '\]'
              scope: punctuation.section.condition.end.dotori
              pop: true
            - match: '\b({{PLATFORM_CONDS}})\b'
              scope: keyword.control.platform.dotori
            - match: '\b({{CONFIG_CONDS}})\b'
              scope: keyword.control.config.dotori
            - match: '\b({{COMPILER_CONDS}})\b'
              scope: keyword.control.compiler.dotori
            - match: '\b({{RUNTIME_CONDS}})\b'
              scope: keyword.control.runtime.dotori
            - match: '\.'
              scope: punctuation.separator.condition.dotori

          top-keywords:
            - match: '\b({{TOP_KEYWORDS}})\b'
              scope: keyword.declaration.dotori

          block-keywords:
            - match: '\b({{BLOCK_KEYWORDS}})\b'
              scope: keyword.other.block.dotori

          property-keywords:
            - match: '\b({{PROPERTY_KEYWORDS}})\b'
              scope: support.type.property-name.dotori

          value-keywords:
            - match: '\b({{TYPE_VALUES}})\b'
              scope: support.constant.type.dotori
            - match: '\b({{STD_VALUES}})\b'
              scope: constant.language.std.dotori
            - match: '\b({{ENUM_VALUES}})\b'
              scope: constant.language.dotori

          numbers:
            - match: '\b\d+\b'
              scope: constant.numeric.integer.dotori

          operators:
            - match: '='
              scope: keyword.operator.assignment.dotori
        """;

    public string Generate()
    {
        var vars = new Dictionary<string, string>
        {
            ["TOP_KEYWORDS"]      = Alt(DotoriGrammarDefinition.TopLevelKeywords),
            ["BLOCK_KEYWORDS"]    = Alt(DotoriGrammarDefinition.BlockKeywords),
            ["PROPERTY_KEYWORDS"] = Alt(DotoriGrammarDefinition.PropertyKeywords),
            ["TYPE_VALUES"]       = Alt(DotoriGrammarDefinition.TypeValues),
            ["STD_VALUES"]        = Alt(DotoriGrammarDefinition.StdValues, escape: true),
            ["ENUM_VALUES"]       = Alt(DotoriGrammarDefinition.EnumValues, escape: true),
            ["PLATFORM_CONDS"]    = Alt(DotoriGrammarDefinition.PlatformConditions),
            ["CONFIG_CONDS"]      = Alt(DotoriGrammarDefinition.ConfigConditions),
            ["COMPILER_CONDS"]    = Alt(DotoriGrammarDefinition.CompilerConditions),
            ["RUNTIME_CONDS"]     = Alt(DotoriGrammarDefinition.RuntimeConditions),
        };
        return TemplateEngine.Render(Template, vars);
    }

    private static string Alt(IEnumerable<string> keywords, bool escape = false) =>
        string.Join("|", escape ? keywords.Select(EscapeYaml) : keywords);

    private static string EscapeYaml(string s) =>
        s.Replace("+", "\\+").Replace(".", "\\.");
}
