namespace Dotori.Core.Grammar;

/// <summary>Tree-sitter grammar.js 생성기.</summary>
/// <remarks>
/// `dotori export grammar --format tree-sitter`로 grammar.js를 생성한 뒤,
/// `tree-sitter generate`를 실행하면 실제 파서(src/parser.c)가 만들어집니다.
/// Zed, Helix, Neovim(nvim-treesitter) 등 Tree-sitter 기반 에디터에서 사용합니다.
/// </remarks>
public sealed class TreeSitterGrammarGenerator : IGrammarGenerator
{
    public string FormatId => "tree-sitter";
    public string DefaultExtension => ".js";

    // grammar.js 템플릿.
    // {{PROP_KEYWORD_CHOICES}}  → project 블록 내 property_stmt 키워드 (JS choice 인수 목록)
    // {{STRING_LIST_CHOICES}}   → 단순 문자열 목록 블록 키워드 (JS choice 인수 목록)
    private const string Template =
        """
        // Dotori DSL — Tree-sitter grammar
        // Generated by `dotori export grammar --format tree-sitter`
        //
        // After regenerating, run:
        //   tree-sitter generate
        // to rebuild src/parser.c

        module.exports = grammar({
          name: 'dotori',

          extras: $ => [
            /\s+/,
            $.comment,
            $.block_comment,
          ],

          rules: {

            // ── Top-level ────────────────────────────────────────────────────────
            source_file: $ => seq(
              optional($.project_decl),
              optional($.package_decl),
            ),

            // ── Comments ─────────────────────────────────────────────────────────
            comment: $ => token(choice(
              seq('#',  /.*/),
              seq('//', /.*/),
            )),

            // Non-nested block comment: (* ... *)
            block_comment: $ => token(seq(
              '(*',
              /([^*]|\*[^)])*\*+/,
              ')',
            )),

            // ── Primitives ───────────────────────────────────────────────────────
            // Identifiers include hyphens and plus signs: c++17, my-lib, static-library
            identifier: $ => token(/[a-zA-Z_][a-zA-Z0-9_\-+]*/),
            integer:    $ => token(/[0-9]+/),
            boolean:    $ => choice('true', 'false'),

            string: $ => seq(
              '"',
              repeat(choice(
                $.string_content,
                $.escape_sequence,
                $.env_interpolation,
              )),
              '"',
            ),
            string_content:    $ => token.immediate(/[^"\\$]+/),
            escape_sequence:   $ => token.immediate(seq('\\', /[nrt"\\/]/)),
            env_interpolation: $ => seq(
              token.immediate('${'),
              field('var_name', token.immediate(/[^}]*/)),
              token.immediate('}'),
            ),

            // ── project declaration ──────────────────────────────────────────────
            project_decl: $ => seq(
              'project',
              field('name', $.identifier),
              '{',
              repeat($.project_item),
              '}',
            ),

            project_item: $ => choice(
              $.condition_block,
              $.property_stmt,
              $.sources_block,
              $.headers_block,
              $.string_list_block,
              $.copy_block,
              $.unity_build_block,
              $.pch_block,
              $.output_block,
              $.dependencies_block,
              $.assembler_block,
              $.option_block,
            ),

            // ── Condition block: [platform.config] { ... } ───────────────────────
            condition_block: $ => seq(
              '[',
              field('condition', $.condition_expr),
              ']',
              '{',
              repeat($.project_item),
              '}',
            ),

            condition_expr: $ => seq(
              $.identifier,
              repeat(seq('.', $.identifier)),
            ),

            // ── property_stmt: key = value ───────────────────────────────────────
            property_stmt: $ => seq(
              field('key', $._prop_keyword),
              '=',
              field('value', $._prop_value),
            ),

            _prop_keyword: $ => choice(
              {{PROP_KEYWORD_CHOICES}}
            ),

            _prop_value: $ => choice(
              $.identifier,
              $.string,
              $.integer,
              $.boolean,
            ),

            // ── sources / modules block ──────────────────────────────────────────
            sources_block: $ => seq(
              field('kind', choice('sources', 'modules')),
              '{',
              repeat($.sources_item),
              '}',
            ),

            sources_item: $ => choice(
              seq(choice('include', 'exclude'), field('pattern', $.string)),
              seq('export-map', '=', field('value', $.boolean)),
            ),

            // ── headers block ────────────────────────────────────────────────────
            headers_block: $ => seq(
              'headers',
              '{',
              repeat($.header_item),
              '}',
            ),

            header_item: $ => seq(
              field('visibility', choice('public', 'private')),
              field('path', $.string),
            ),

            // ── simple string-list blocks ────────────────────────────────────────
            // defines, links, frameworks, framework-paths, compile-flags,
            // link-flags, resources, pre-build, post-build, emscripten-flags
            string_list_block: $ => seq(
              field('kind', $._string_list_keyword),
              '{',
              repeat($.string),
              '}',
            ),

            _string_list_keyword: $ => choice(
              {{STRING_LIST_CHOICES}}
            ),

            // ── copy block ───────────────────────────────────────────────────────
            copy_block: $ => seq(
              'copy',
              '{',
              repeat($.copy_item),
              '}',
            ),

            copy_item: $ => seq(
              'from', field('from', $.string),
              'to',   field('to',   $.string),
            ),

            // ── unity-build block ────────────────────────────────────────────────
            unity_build_block: $ => seq(
              'unity-build',
              '{',
              repeat(choice(
                seq('enabled',    '=', field('enabled',    $.boolean)),
                seq('batch-size', '=', field('batch_size', $.integer)),
                seq('exclude', '{', repeat($.string), '}'),
              )),
              '}',
            ),

            // ── pch block ────────────────────────────────────────────────────────
            pch_block: $ => seq(
              'pch',
              '{',
              repeat(choice(
                seq('header',  '=', field('header',  $.string)),
                seq('source',  '=', field('source',  $.string)),
                seq('modules', '=', field('modules', $.boolean)),
              )),
              '}',
            ),

            // ── output block ─────────────────────────────────────────────────────
            output_block: $ => seq(
              'output',
              '{',
              repeat(choice(
                seq('binaries',  '=', field('binaries',  $.string)),
                seq('libraries', '=', field('libraries', $.string)),
                seq('symbols',   '=', field('symbols',   $.string)),
              )),
              '}',
            ),

            // ── dependencies block ───────────────────────────────────────────────
            dependencies_block: $ => seq(
              'dependencies',
              '{',
              repeat($.dep_item),
              '}',
            ),

            dep_item: $ => seq(
              field('name', $.dep_name),
              '=',
              field('value', $.dep_value),
            ),

            // Supports: libname = "1.0"  or  owner/pkg = "1.0"
            dep_name: $ => choice(
              $.identifier,
              seq($.identifier, '/', $.identifier),
            ),

            dep_value: $ => choice(
              $.string,
              $.dep_object,
            ),

            dep_object: $ => seq(
              '{',
              repeat(seq($.dep_field, optional(','))),
              '}',
            ),

            dep_field: $ => choice(
              seq(
                choice('git', 'tag', 'commit', 'path', 'version'),
                '=',
                field('value', $.string),
              ),
              seq(
                'option',
                '=',
                choice(
                  $.string,
                  seq('{', repeat($.string), '}'),
                ),
              ),
            ),

            // ── assembler block ──────────────────────────────────────────────────
            assembler_block: $ => seq(
              'assembler',
              '{',
              repeat($.assembler_item),
              '}',
            ),

            assembler_item: $ => choice(
              seq('tool',   '=', field('value', $.identifier)),
              seq('format', '=', field('value', $.identifier)),
              seq(choice('include', 'exclude'), field('pattern', $.string)),
              seq('flags',   '{', repeat($.string), '}'),
              seq('defines', '{', repeat($.string), '}'),
            ),

            // ── option block ─────────────────────────────────────────────────────
            option_block: $ => seq(
              'option',
              field('name', $.identifier),
              '{',
              repeat($.option_field),
              '}',
            ),

            option_field: $ => choice(
              seq('default',      '=', field('value', $.boolean)),
              seq('defines',      '{', repeat($.string), '}'),
              seq('dependencies', '{', repeat($.dep_item), '}'),
            ),

            // ── package declaration ──────────────────────────────────────────────
            package_decl: $ => seq(
              'package',
              '{',
              repeat($.package_item),
              '}',
            ),

            package_item: $ => choice(
              seq('name',        '=', field('value', $.string)),
              seq('version',     '=', field('value', $.string)),
              seq('description', '=', field('value', $.string)),
              seq('license',     '=', field('value', $.string)),
              seq('homepage',    '=', field('value', $.string)),
              $.authors_block,
              $.exports_block,
            ),

            authors_block: $ => seq(
              'authors',
              '{',
              repeat($.string),
              '}',
            ),

            exports_block: $ => seq(
              'exports',
              '{',
              repeat($.export_entry),
              '}',
            ),

            export_entry: $ => seq(
              field('key',   $.identifier),
              '=',
              field('value', $.string),
            ),

          }, // end rules
        });
        """;

    public string Generate()
    {
        var vars = new Dictionary<string, string>
        {
            ["PROP_KEYWORD_CHOICES"]  = JsChoiceArgs(DotoriGrammarDefinition.ProjectPropertyKeywords),
            ["STRING_LIST_CHOICES"]   = JsChoiceArgs(DotoriGrammarDefinition.StringListBlockKeywords),
        };
        return TemplateEngine.Render(Template, vars);
    }

    /// <summary>키워드 목록을 JS choice() 인수 형태로 변환합니다. 예: 'type', 'std', 'description'</summary>
    private static string JsChoiceArgs(IEnumerable<string> keywords) =>
        string.Join(",\n              ", keywords.Select(k => $"'{k}'"));
}
