using System.Text;

namespace Dotori.Core.Grammar;

/// <summary>Vim syntax 파일 (.vim) 생성기.</summary>
/// <remarks>Vim 및 Neovim (Tree-sitter 미설치 시)에서 사용합니다.</remarks>
public sealed class VimSyntaxGenerator : IGrammarGenerator
{
    public string FormatId => "vim";
    public string DefaultExtension => ".vim";

    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("\" Vim syntax file for Dotori build system (.dotori)");
        sb.AppendLine("\" Generated by `dotori export grammar --format vim`");
        sb.AppendLine("\" Language: Dotori DSL");
        sb.AppendLine();
        sb.AppendLine("if exists('b:current_syntax')");
        sb.AppendLine("  finish");
        sb.AppendLine("endif");
        sb.AppendLine();

        // 주석
        sb.AppendLine("\" Comments");
        sb.AppendLine("syntax match   dotoriComment  /#.*$/");
        sb.AppendLine("syntax match   dotoriComment  /\\/\\/.*/");
        sb.AppendLine("syntax region  dotoriComment  start=/(\\*/ end=/\\*)/");
        sb.AppendLine();

        // 문자열 (${VAR} 보간 포함)
        sb.AppendLine("\" Strings");
        sb.AppendLine("syntax region  dotoriString   start=/\"/ end=/\"/ contains=dotoriEnvVar,dotoriEscape");
        sb.AppendLine("syntax match   dotoriEnvVar   /\\${[^}]*}/ contained");
        sb.AppendLine("syntax match   dotoriEscape   /\\\\./ contained");
        sb.AppendLine();

        // 숫자
        sb.AppendLine("\" Numbers");
        sb.AppendLine("syntax match   dotoriNumber   /\\b\\d\\+\\b/");
        sb.AppendLine();

        // 최상위 키워드
        sb.AppendLine("\" Top-level keywords");
        sb.AppendLine($"syntax keyword dotoriKeyword  {string.Join(" ", DotoriGrammarDefinition.TopLevelKeywords)}");
        sb.AppendLine();

        // 블록 키워드
        sb.AppendLine("\" Block keywords");
        AppendKeywordLines(sb, "dotoriBlock", DotoriGrammarDefinition.BlockKeywords);
        sb.AppendLine();

        // 프로퍼티 키워드
        sb.AppendLine("\" Property keywords");
        AppendKeywordLines(sb, "dotoriProp", DotoriGrammarDefinition.PropertyKeywords);
        sb.AppendLine();

        // 열거형 값
        sb.AppendLine("\" Type values");
        AppendKeywordLines(sb, "dotoriType", DotoriGrammarDefinition.TypeValues);
        sb.AppendLine();

        sb.AppendLine("\" Standard values");
        sb.AppendLine($"syntax match   dotoriStd      /c++17\\|c++20\\|c++23/");
        sb.AppendLine();

        sb.AppendLine("\" Enum / constant values");
        AppendKeywordLines(sb, "dotoriConst", DotoriGrammarDefinition.EnumValues.Where(v => !v.Contains('+')));
        sb.AppendLine();

        // 조건 블록 ([...])
        sb.AppendLine("\" Condition blocks  [ ... ]");
        sb.AppendLine("syntax region  dotoriCond     start=/\\[/ end=/\\]/ contains=dotoriCondAtom,dotoriCondSep");
        sb.AppendLine($"syntax keyword dotoriCondAtom contained {string.Join(" ", DotoriGrammarDefinition.PlatformConditions)}");
        sb.AppendLine($"syntax keyword dotoriCondAtom contained {string.Join(" ", DotoriGrammarDefinition.ConfigConditions)}");
        sb.AppendLine($"syntax keyword dotoriCondAtom contained {string.Join(" ", DotoriGrammarDefinition.CompilerConditions)}");
        sb.AppendLine($"syntax keyword dotoriCondAtom contained {string.Join(" ", DotoriGrammarDefinition.RuntimeConditions)}");
        sb.AppendLine("syntax match   dotoriCondSep  /\\./ contained");
        sb.AppendLine();

        // 연산자
        sb.AppendLine("\" Operators");
        sb.AppendLine("syntax match   dotoriOp       /=/");
        sb.AppendLine();

        // 색상 링크
        sb.AppendLine("\" Highlight links");
        sb.AppendLine("hi def link  dotoriComment   Comment");
        sb.AppendLine("hi def link  dotoriString    String");
        sb.AppendLine("hi def link  dotoriEnvVar    Special");
        sb.AppendLine("hi def link  dotoriEscape    SpecialChar");
        sb.AppendLine("hi def link  dotoriNumber    Number");
        sb.AppendLine("hi def link  dotoriKeyword   Keyword");
        sb.AppendLine("hi def link  dotoriBlock     Statement");
        sb.AppendLine("hi def link  dotoriProp      Identifier");
        sb.AppendLine("hi def link  dotoriType      Type");
        sb.AppendLine("hi def link  dotoriStd       Constant");
        sb.AppendLine("hi def link  dotoriConst     Constant");
        sb.AppendLine("hi def link  dotoriCond      PreProc");
        sb.AppendLine("hi def link  dotoriCondAtom  PreCondit");
        sb.AppendLine("hi def link  dotoriCondSep   Delimiter");
        sb.AppendLine("hi def link  dotoriOp        Operator");
        sb.AppendLine();

        sb.AppendLine("let b:current_syntax = 'dotori'");

        return sb.ToString();
    }

    /// <summary>키워드가 많을 때 줄 길이를 맞춰 여러 줄로 나눕니다.</summary>
    private static void AppendKeywordLines(StringBuilder sb, string group, IEnumerable<string> keywords)
    {
        const int maxPerLine = 8;
        var batch = new List<string>();
        foreach (var kw in keywords)
        {
            batch.Add(kw);
            if (batch.Count >= maxPerLine)
            {
                sb.AppendLine($"syntax keyword {group,-14} {string.Join(" ", batch)}");
                batch.Clear();
            }
        }
        if (batch.Count > 0)
            sb.AppendLine($"syntax keyword {group,-14} {string.Join(" ", batch)}");
    }
}
