namespace Dotori.Core.Grammar;

/// <summary>Vim syntax 파일 (.vim) 생성기.</summary>
/// <remarks>Vim 및 Neovim (Tree-sitter 미설치 시)에서 사용합니다.</remarks>
public sealed class VimSyntaxGenerator : IGrammarGenerator
{
    public string FormatId => "vim";
    public string DefaultExtension => ".vim";

    private const string Template = """
        " Vim syntax file for Dotori build system (.dotori)
        " Generated by `dotori export grammar --format vim`
        " Language: Dotori DSL
        " Place in: ~/.vim/syntax/dotori.vim  (or nvim equivalent)

        if exists('b:current_syntax')
          finish
        endif

        " ── Comments ──────────────────────────────────────────────────────────────
        syntax match   dotoriComment  /#.*$/
        syntax match   dotoriComment  /\/\/.*/
        syntax region  dotoriComment  start=/(\\*/ end=/\\*)/

        " ── Strings (with ${VAR} interpolation) ──────────────────────────────────
        syntax region  dotoriString   start=/"/ end=/"/ contains=dotoriEnvVar,dotoriEscape
        syntax match   dotoriEnvVar   /\${[^}]*}/ contained
        syntax match   dotoriEscape   /\\./ contained

        " ── Numbers ───────────────────────────────────────────────────────────────
        syntax match   dotoriNumber   /\b\d\+\b/

        " ── Top-level keywords ────────────────────────────────────────────────────
        syntax keyword dotoriKeyword  {{TOP_KEYWORDS}}

        " ── Block keywords ────────────────────────────────────────────────────────
        {{BLOCK_KEYWORD_LINES}}

        " ── Property keywords ─────────────────────────────────────────────────────
        {{PROPERTY_KEYWORD_LINES}}

        " ── Type values ───────────────────────────────────────────────────────────
        {{TYPE_VALUE_LINES}}

        " ── C++ standard values ───────────────────────────────────────────────────
        syntax match   dotoriStd      /c++17\|c++20\|c++23/

        " ── Enum / constant values ────────────────────────────────────────────────
        {{ENUM_VALUE_LINES}}

        " ── Condition blocks  [ ... ] ─────────────────────────────────────────────
        syntax region  dotoriCond     start=/\[/ end=/\]/ contains=dotoriCondAtom,dotoriCondSep
        syntax keyword dotoriCondAtom contained {{ALL_COND_ATOMS}}
        syntax match   dotoriCondSep  /\./ contained

        " ── Operators ─────────────────────────────────────────────────────────────
        syntax match   dotoriOp       /=/

        " ── Highlight links ───────────────────────────────────────────────────────
        hi def link  dotoriComment   Comment
        hi def link  dotoriString    String
        hi def link  dotoriEnvVar    Special
        hi def link  dotoriEscape    SpecialChar
        hi def link  dotoriNumber    Number
        hi def link  dotoriKeyword   Keyword
        hi def link  dotoriBlock     Statement
        hi def link  dotoriProp      Identifier
        hi def link  dotoriType      Type
        hi def link  dotoriStd       Constant
        hi def link  dotoriConst     Constant
        hi def link  dotoriCond      PreProc
        hi def link  dotoriCondAtom  PreCondit
        hi def link  dotoriCondSep   Delimiter
        hi def link  dotoriOp        Operator

        let b:current_syntax = 'dotori'
        """;

    public string Generate()
    {
        var allConds = DotoriGrammarDefinition.PlatformConditions
            .Concat(DotoriGrammarDefinition.ConfigConditions)
            .Concat(DotoriGrammarDefinition.CompilerConditions)
            .Concat(DotoriGrammarDefinition.RuntimeConditions)
            .Distinct();

        var vars = new Dictionary<string, string>
        {
            ["TOP_KEYWORDS"]         = string.Join(" ", DotoriGrammarDefinition.TopLevelKeywords),
            ["BLOCK_KEYWORD_LINES"]  = KeywordLines("dotoriBlock", DotoriGrammarDefinition.BlockKeywords),
            ["PROPERTY_KEYWORD_LINES"] = KeywordLines("dotoriProp", DotoriGrammarDefinition.PropertyKeywords),
            ["TYPE_VALUE_LINES"]     = KeywordLines("dotoriType", DotoriGrammarDefinition.TypeValues),
            ["ENUM_VALUE_LINES"]     = KeywordLines("dotoriConst",
                                          DotoriGrammarDefinition.EnumValues.Where(v => !v.Contains('+'))),
            ["ALL_COND_ATOMS"]       = string.Join(" ", allConds),
        };
        return TemplateEngine.Render(Template, vars);
    }

    /// <summary>키워드가 많을 때 줄 길이를 맞춰 여러 줄의 <c>syntax keyword</c>로 나눕니다.</summary>
    private static string KeywordLines(string group, IEnumerable<string> keywords)
    {
        const int maxPerLine = 8;
        var lines = new List<string>();
        var batch = new List<string>();
        foreach (var kw in keywords)
        {
            batch.Add(kw);
            if (batch.Count >= maxPerLine)
            {
                lines.Add($"syntax keyword {group,-14} {string.Join(" ", batch)}");
                batch.Clear();
            }
        }
        if (batch.Count > 0)
            lines.Add($"syntax keyword {group,-14} {string.Join(" ", batch)}");
        return string.Join("\n", lines);
    }
}
