namespace Dotori.Core.Grammar;

/// <summary>Zed/Helix/Neovim(nvim-treesitter) 용 Tree-sitter highlights.scm 생성기.</summary>
/// <remarks>
/// 주의: highlights.scm은 Tree-sitter 파서(grammar.js)가 이미 빌드되어 있어야 실제 동작합니다.
/// 이 파일 단독으로는 구문 강조가 적용되지 않으며, dotori Tree-sitter 문법과 함께 사용해야 합니다.
/// </remarks>
public sealed class ZedHighlightGenerator : IGrammarGenerator
{
    public string FormatId => "zed";
    public string DefaultExtension => ".scm";

    private const string Template = """
        ; Dotori DSL — Tree-sitter highlights
        ; Generated by `dotori export grammar --format zed`
        ;
        ; NOTE: This file requires a compiled Tree-sitter parser for Dotori.
        ; Used by: Zed, Helix, Neovim (nvim-treesitter)

        ; ── Comments ──────────────────────────────────────────────────────────────
        (comment) @comment
        (block_comment) @comment.block

        ; ── String literals ───────────────────────────────────────────────────────
        (string) @string
        (escape_sequence) @string.escape
        (env_interpolation) @string.special

        ; ── Numbers ───────────────────────────────────────────────────────────────
        (integer) @number

        ; ── Top-level declarations ────────────────────────────────────────────────
        {{TOP_KEYWORD_NODES}}

        ; ── Block keywords ────────────────────────────────────────────────────────
        [
        {{BLOCK_KEYWORD_LIST}}
        ] @keyword

        ; ── Property keywords (left side of `=`) ─────────────────────────────────
        [
        {{PROPERTY_KEYWORD_LIST}}
        ] @variable.member

        ; ── Type values ───────────────────────────────────────────────────────────
        [
        {{TYPE_VALUE_LIST}}
        ] @type

        ; ── C++ standard values ───────────────────────────────────────────────────
        [
        {{STD_VALUE_LIST}}
        ] @constant.builtin

        ; ── Enum / constant values ────────────────────────────────────────────────
        [
        {{ENUM_VALUE_LIST}}
        ] @constant.builtin

        ; ── Condition block ───────────────────────────────────────────────────────
        (condition_block
          "[" @punctuation.bracket
          (condition_expr) @attribute
          "]" @punctuation.bracket)

        ; Platform / config / compiler / runtime atoms inside conditions
        [
        {{COND_ATOM_LIST}}
        ] @tag

        ; ── Operators & punctuation ───────────────────────────────────────────────
        "=" @operator
        "." @punctuation.delimiter
        "," @punctuation.delimiter

        "{" @punctuation.bracket
        "}" @punctuation.bracket
        "[" @punctuation.bracket
        "]" @punctuation.bracket

        ; ── Project / package name after keyword ──────────────────────────────────
        (project_decl name: (identifier) @type)

        ; ── Dependency names (left side of dep = {...}) ───────────────────────────
        (dep_item name: (identifier) @variable.member)

        ; ── Option names ──────────────────────────────────────────────────────────
        (option_block name: (identifier) @variable.other)

        ; ── General identifiers ───────────────────────────────────────────────────
        (identifier) @variable
        """;

    public string Generate()
    {
        var allConds = DotoriGrammarDefinition.PlatformConditions
            .Concat(DotoriGrammarDefinition.ConfigConditions)
            .Concat(DotoriGrammarDefinition.CompilerConditions)
            .Concat(DotoriGrammarDefinition.RuntimeConditions)
            .Distinct();

        var vars = new Dictionary<string, string>
        {
            ["TOP_KEYWORD_NODES"]    = TopKeywordNodes(),
            ["BLOCK_KEYWORD_LIST"]   = QuotedList(DotoriGrammarDefinition.BlockKeywords),
            ["PROPERTY_KEYWORD_LIST"] = QuotedList(DotoriGrammarDefinition.PropertyKeywords),
            ["TYPE_VALUE_LIST"]      = QuotedList(DotoriGrammarDefinition.TypeValues),
            ["STD_VALUE_LIST"]       = QuotedList(DotoriGrammarDefinition.StdValues),
            ["ENUM_VALUE_LIST"]      = QuotedList(DotoriGrammarDefinition.EnumValues),
            ["COND_ATOM_LIST"]       = QuotedList(allConds),
        };
        return TemplateEngine.Render(Template, vars);
    }

    private static string TopKeywordNodes() =>
        string.Join("\n", DotoriGrammarDefinition.TopLevelKeywords
            .Select(kw => $"(\"{kw}\") @keyword.declaration"));

    private static string QuotedList(IEnumerable<string> keywords) =>
        string.Join("\n", keywords.Select(kw => $"  \"{kw}\""));
}
