using System.Text;

namespace Dotori.Core.Grammar;

/// <summary>Zed/Helix/Neovim(nvim-treesitter) 용 Tree-sitter highlights.scm 생성기.</summary>
/// <remarks>
/// 주의: highlights.scm은 Tree-sitter 파서(grammar.js)가 이미 빌드되어 있어야 실제 동작합니다.
/// 이 파일 단독으로는 구문 강조가 적용되지 않으며, dotori Tree-sitter 문법과 함께 사용해야 합니다.
/// </remarks>
public sealed class ZedHighlightGenerator : IGrammarGenerator
{
    public string FormatId => "zed";
    public string DefaultExtension => ".scm";

    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("; Dotori DSL — Tree-sitter highlights");
        sb.AppendLine("; Generated by `dotori export grammar --format zed`");
        sb.AppendLine(";");
        sb.AppendLine("; NOTE: This file requires a compiled Tree-sitter parser for Dotori.");
        sb.AppendLine("; Used by: Zed, Helix, Neovim (nvim-treesitter)");
        sb.AppendLine();

        // 주석
        sb.AppendLine("; ── Comments ─────────────────────────────────────────────────────────────");
        sb.AppendLine("(comment) @comment");
        sb.AppendLine("(block_comment) @comment.block");
        sb.AppendLine();

        // 문자열
        sb.AppendLine("; ── Strings ──────────────────────────────────────────────────────────────");
        sb.AppendLine("(string) @string");
        sb.AppendLine("(escape_sequence) @string.escape");
        sb.AppendLine("(env_interpolation) @string.special");
        sb.AppendLine();

        // 숫자
        sb.AppendLine("; ── Numbers ──────────────────────────────────────────────────────────────");
        sb.AppendLine("(integer) @number");
        sb.AppendLine();

        // 최상위 선언 키워드
        sb.AppendLine("; ── Top-level declarations ───────────────────────────────────────────────");
        foreach (var kw in DotoriGrammarDefinition.TopLevelKeywords)
            sb.AppendLine($"(\"{kw}\") @keyword");
        sb.AppendLine();

        // 블록 키워드
        sb.AppendLine("; ── Block keywords ───────────────────────────────────────────────────────");
        foreach (var kw in DotoriGrammarDefinition.BlockKeywords)
            sb.AppendLine($"(\"{kw}\") @keyword");
        sb.AppendLine();

        // 프로퍼티 키워드
        sb.AppendLine("; ── Property keywords ────────────────────────────────────────────────────");
        foreach (var kw in DotoriGrammarDefinition.PropertyKeywords)
            sb.AppendLine($"(\"{kw}\") @variable.member");
        sb.AppendLine();

        // 타입 값
        sb.AppendLine("; ── Type values ──────────────────────────────────────────────────────────");
        foreach (var v in DotoriGrammarDefinition.TypeValues)
            sb.AppendLine($"(\"{v}\") @type");
        sb.AppendLine();

        // std 값
        sb.AppendLine("; ── C++ standard values ──────────────────────────────────────────────────");
        foreach (var v in DotoriGrammarDefinition.StdValues)
            sb.AppendLine($"(\"{v}\") @constant.builtin");
        sb.AppendLine();

        // 열거형 값
        sb.AppendLine("; ── Enum / constant values ───────────────────────────────────────────────");
        foreach (var v in DotoriGrammarDefinition.EnumValues)
            sb.AppendLine($"(\"{v}\") @constant.builtin");
        sb.AppendLine();

        // 조건 블록 atom
        sb.AppendLine("; ── Condition block atoms  [ ... ] ───────────────────────────────────────");
        sb.AppendLine("; Platform");
        foreach (var a in DotoriGrammarDefinition.PlatformConditions)
            sb.AppendLine($"(\"{a}\") @attribute");
        sb.AppendLine("; Config");
        foreach (var a in DotoriGrammarDefinition.ConfigConditions)
            sb.AppendLine($"(\"{a}\") @attribute");
        sb.AppendLine("; Compiler");
        foreach (var a in DotoriGrammarDefinition.CompilerConditions)
            sb.AppendLine($"(\"{a}\") @attribute");
        sb.AppendLine("; Runtime");
        foreach (var a in DotoriGrammarDefinition.RuntimeConditions)
            sb.AppendLine($"(\"{a}\") @attribute");
        sb.AppendLine();

        // 구두점
        sb.AppendLine("; ── Punctuation ──────────────────────────────────────────────────────────");
        sb.AppendLine("\"{\" @punctuation.bracket");
        sb.AppendLine("\"}\" @punctuation.bracket");
        sb.AppendLine("\"[\" @punctuation.bracket");
        sb.AppendLine("\"]\" @punctuation.bracket");
        sb.AppendLine("\".\" @punctuation.delimiter");
        sb.AppendLine("\"=\" @operator");
        sb.AppendLine("\",\" @punctuation.delimiter");

        return sb.ToString();
    }
}
