; Dotori DSL — Tree-sitter highlights
; Generated by `dotori export grammar --format zed`
;
; NOTE: This file requires a compiled Tree-sitter parser for Dotori.
;       Run `dotori export grammar --format tree-sitter` to generate grammar.js,
;       then `tree-sitter generate` to build the parser.
; Used by: Zed, Helix, Neovim (nvim-treesitter)

; ── Comments ──────────────────────────────────────────────────────────────
(comment)       @comment
(block_comment) @comment.block

; ── String literals ───────────────────────────────────────────────────────
(string)            @string
(escape_sequence)   @string.escape
(env_interpolation) @string.special

; ── Numbers ───────────────────────────────────────────────────────────────
(integer) @number

; ── Booleans ──────────────────────────────────────────────────────────────
(boolean) @constant.builtin

; ── Top-level declaration keywords ────────────────────────────────────────
(project_decl "project" @keyword.declaration)
(package_decl "package" @keyword.declaration)

; ── Block keywords (via node type) ────────────────────────────────────────
(sources_block       kind: _ @keyword)
(headers_block       "headers" @keyword)
(string_list_block   kind: _ @keyword)
(copy_block          "copy" @keyword)
(unity_build_block   "unity-build" @keyword)
(pch_block           "pch" @keyword)
(output_block        "output" @keyword)
(dependencies_block  "dependencies" @keyword)
(assembler_block     "assembler" @keyword)
(option_block        "option" @keyword)
(authors_block       "authors" @keyword)
(exports_block       "exports" @keyword)

; ── Property keywords (left side of `=`) ─────────────────────────────────
(property_stmt key: _ @variable.member)

; ── Block-internal field keywords ─────────────────────────────────────────
(sources_item   ["include" "exclude" "export-map"] @variable.member)
(header_item    visibility: _ @variable.member)
(copy_item      ["from" "to"] @variable.member)
(dep_field      ["git" "tag" "commit" "path" "version" "option"] @variable.member)
(assembler_item ["tool" "format" "include" "exclude" "flags" "defines"] @variable.member)
(option_field   ["default" "defines" "dependencies"] @variable.member)
(unity_build_block ["enabled" "batch-size" "exclude"] @variable.member)
(pch_block         ["header" "source" "modules"] @variable.member)
(output_block      ["binaries" "libraries" "symbols"] @variable.member)

; ── package field keywords ────────────────────────────────────────────────
(package_item ["name" "version" "description" "license" "homepage"] @variable.member)
(export_entry key: (identifier) @variable.member)

; ── Type values (type = ...) ──────────────────────────────────────────────
[
  "executable"
  "static-library"
  "shared-library"
  "header-only"
] @type

; ── C++ standard values (std = ...) ───────────────────────────────────────
[
  "c++17"
  "c++20"
  "c++23"
] @constant.builtin

; ── Enum / constant values ────────────────────────────────────────────────
[
  "none"
  "size"
  "speed"
  "full"
  "minimal"
  "static"
  "dynamic"
  "glibc"
  "musl"
  "libc++"
  "libstdc++"
  "default"
  "all"
  "extra"
  "true"
  "false"
  "nasm"
  "yasm"
  "gas"
  "as"
  "masm"
  "auto"
  "elf64"
  "elf32"
  "win64"
  "win32"
  "macho64"
  "macho32"
] @constant.builtin

; ── Condition block ───────────────────────────────────────────────────────
(condition_block
  "[" @punctuation.bracket
  (condition_expr) @attribute
  "]" @punctuation.bracket)

; ── Project / option names ────────────────────────────────────────────────
(project_decl name: (identifier) @type)
(option_block name: (identifier) @variable.other)

; ── Dependency names ──────────────────────────────────────────────────────
(dep_item name: (dep_name) @variable.member)

; ── Operators & punctuation ───────────────────────────────────────────────
"=" @operator
"." @punctuation.delimiter
"/" @punctuation.delimiter

"{" @punctuation.bracket
"}" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket

; ── General identifiers (fallback) ────────────────────────────────────────
(identifier) @variable