using System.Text;
using Dotori.Core.Model;
using Dotori.Core.Parsing;

namespace Dotori.Core.Generators;

/// <summary>
/// Generates CMakeLists.txt from a flattened project model.
/// Supports single-config and dual-config (debug+release) generation.
/// Dependencies: path → add_subdirectory, git → FetchContent, version → comment.
/// </summary>
public sealed class CMakeGenerator : IBuildSystemGenerator
{
    public string FormatId => "cmake";

    public IReadOnlyList<(string RelativePath, string Content)> Generate(
        FlatProjectModel model,
        string config,
        string targetId)
    {
        var sb = new StringBuilder();
        WriteCMakeLists(sb, model, config, targetId);
        return [("CMakeLists.txt", sb.ToString())];
    }

    private static void WriteCMakeLists(StringBuilder sb, FlatProjectModel model, string config, string targetId)
    {
        sb.AppendLine("# Generated by dotori export build-system --format cmake");
        sb.AppendLine("# Do not edit manually — re-run the command to regenerate.");
        sb.AppendLine();

        sb.AppendLine("cmake_minimum_required(VERSION 3.21)");
        sb.AppendLine($"project({EscapeName(model.Name)})");
        sb.AppendLine();

        // Git dependencies via FetchContent
        WriteFetchContent(sb, model);

        // Path dependencies via add_subdirectory
        WriteSubdirectories(sb, model);

        // Target declaration
        WriteTargetDeclaration(sb, model);

        // C++ standard
        var stdNum = model.Std switch
        {
            CxxStd.Cxx17 => "17",
            CxxStd.Cxx20 => "20",
            CxxStd.Cxx23 => "23",
            _             => "23",
        };
        sb.AppendLine($"set_target_properties({EscapeName(model.Name)} PROPERTIES");
        sb.AppendLine($"    CXX_STANDARD {stdNum}");
        sb.AppendLine("    CXX_STANDARD_REQUIRED ON");
        sb.AppendLine("    CXX_EXTENSIONS OFF");
        sb.AppendLine(")");
        sb.AppendLine();

        // Include directories
        WriteIncludeDirectories(sb, model);

        // Compile definitions
        if (model.Defines.Count > 0)
        {
            sb.AppendLine($"target_compile_definitions({EscapeName(model.Name)} PRIVATE");
            foreach (var def in model.Defines)
                sb.AppendLine($"    {def}");
            sb.AppendLine(")");
            sb.AppendLine();
        }

        // Compile options
        WriteCompileOptions(sb, model, config);

        // Link libraries
        WriteLinkLibraries(sb, model);

        // Link options
        if (model.LinkFlags.Count > 0)
        {
            sb.AppendLine($"target_link_options({EscapeName(model.Name)} PRIVATE");
            foreach (var flag in model.LinkFlags)
                sb.AppendLine($"    {flag}");
            sb.AppendLine(")");
            sb.AppendLine();
        }

        // PCH
        if (model.Pch?.Header is not null)
        {
            sb.AppendLine($"target_precompile_headers({EscapeName(model.Name)} PRIVATE");
            sb.AppendLine($"    {model.Pch.Header}");
            sb.AppendLine(")");
            sb.AppendLine();
        }

        // Unity build
        if (model.UnityBuild?.Enabled == true)
        {
            sb.AppendLine($"set_target_properties({EscapeName(model.Name)} PROPERTIES UNITY_BUILD ON)");
            if (model.UnityBuild.BatchSize > 0)
                sb.AppendLine($"set_target_properties({EscapeName(model.Name)} PROPERTIES UNITY_BUILD_BATCH_SIZE {model.UnityBuild.BatchSize})");
            sb.AppendLine();
        }

        // Output directories
        if (model.Output is not null)
        {
            WriteOutputDirectories(sb, model);
        }

        // macOS minimum version
        if (model.MacosMin is not null)
        {
            sb.AppendLine($"if(APPLE)");
            sb.AppendLine($"    set(CMAKE_OSX_DEPLOYMENT_TARGET \"{model.MacosMin}\")");
            sb.AppendLine("endif()");
            sb.AppendLine();
        }

        // LTO
        if (model.Lto)
        {
            sb.AppendLine($"set_target_properties({EscapeName(model.Name)} PROPERTIES");
            sb.AppendLine("    INTERPROCEDURAL_OPTIMIZATION ON");
            sb.AppendLine(")");
            sb.AppendLine();
        }

        // Pre/Post build commands
        WriteCustomCommands(sb, model);

        // Version dependency hint
        WriteVersionDependencyHints(sb, model);
    }

    private static void WriteTargetDeclaration(StringBuilder sb, FlatProjectModel model)
    {
        var sources = ExpandGlobs(model);

        var targetName = EscapeName(model.Name);

        if (model.Type == ProjectType.HeaderOnly)
        {
            sb.AppendLine($"add_library({targetName} INTERFACE)");
            sb.AppendLine();
            return;
        }

        var typeKeyword = model.Type switch
        {
            ProjectType.Executable    => $"add_executable({targetName}",
            ProjectType.StaticLibrary => $"add_library({targetName} STATIC",
            ProjectType.SharedLibrary => $"add_library({targetName} SHARED",
            _                         => $"add_executable({targetName}",
        };

        if (sources.Count == 0)
        {
            sb.AppendLine($"{typeKeyword})");
        }
        else
        {
            sb.AppendLine($"{typeKeyword}");
            foreach (var src in sources)
                sb.AppendLine($"    {src}");
            sb.AppendLine(")");
        }
        sb.AppendLine();
    }

    private static void WriteIncludeDirectories(StringBuilder sb, FlatProjectModel model)
    {
        var publicHeaders  = model.Headers.Where(h => h.IsPublic).Select(h => h.Path).ToList();
        var privateHeaders = model.Headers.Where(h => !h.IsPublic).Select(h => h.Path).ToList();

        if (publicHeaders.Count == 0 && privateHeaders.Count == 0) return;

        var targetName = EscapeName(model.Name);
        var visibility = model.Type == ProjectType.HeaderOnly ? "INTERFACE" : null;

        if (publicHeaders.Count > 0)
        {
            var vis = visibility ?? "PUBLIC";
            sb.AppendLine($"target_include_directories({targetName} {vis}");
            foreach (var h in publicHeaders)
                sb.AppendLine($"    {h}");
            sb.AppendLine(")");
        }

        if (privateHeaders.Count > 0 && model.Type != ProjectType.HeaderOnly)
        {
            sb.AppendLine($"target_include_directories({targetName} PRIVATE");
            foreach (var h in privateHeaders)
                sb.AppendLine($"    {h}");
            sb.AppendLine(")");
        }

        sb.AppendLine();
    }

    private static void WriteCompileOptions(StringBuilder sb, FlatProjectModel model, string config)
    {
        var flags = new List<string>(model.CompileFlags);

        // Optimization flags via generator expressions when config == "both"
        if (config == "both")
        {
            var releaseOpt = model.Optimize switch
            {
                OptimizeLevel.Size  => "$<$<CONFIG:Release>:-Os>",
                OptimizeLevel.Speed => "$<$<CONFIG:Release>:-O2>",
                OptimizeLevel.Full  => "$<$<CONFIG:Release>:-O3>",
                _                   => null,
            };
            if (releaseOpt is not null) flags.Add(releaseOpt);

            if (model.DebugInfo != DebugInfoLevel.None)
            {
                var dbgFlag = model.DebugInfo == DebugInfoLevel.Full ? "-g" : "-g1";
                flags.Add($"$<$<CONFIG:Debug>:{dbgFlag}>");
            }
        }
        else
        {
            // Single config
            var optFlag = model.Optimize switch
            {
                OptimizeLevel.Size  => "-Os",
                OptimizeLevel.Speed => "-O2",
                OptimizeLevel.Full  => "-O3",
                _                   => null,
            };
            if (optFlag is not null) flags.Add(optFlag);

            if (model.DebugInfo != DebugInfoLevel.None)
                flags.Add(model.DebugInfo == DebugInfoLevel.Full ? "-g" : "-g1");
        }

        // Warnings
        var warnFlag = model.Warnings switch
        {
            WarningLevel.None    => "-w",
            WarningLevel.All     => "-Wall",
            WarningLevel.Extra   => "-Wall -Wextra",
            _                    => null,
        };
        if (warnFlag is not null) flags.Add(warnFlag);
        if (model.WarningsAsErrors) flags.Add("-Werror");

        if (flags.Count == 0) return;

        sb.AppendLine($"target_compile_options({EscapeName(model.Name)} PRIVATE");
        foreach (var f in flags)
            sb.AppendLine($"    {f}");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void WriteLinkLibraries(StringBuilder sb, FlatProjectModel model)
    {
        if (model.Links.Count == 0 && model.Frameworks.Count == 0 && model.Dependencies.Count == 0)
            return;

        var targetName = EscapeName(model.Name);
        var visibility = model.Type == ProjectType.HeaderOnly ? "INTERFACE" : "PRIVATE";

        sb.AppendLine($"target_link_libraries({targetName} {visibility}");

        foreach (var lib in model.Links)
            sb.AppendLine($"    {lib}");

        foreach (var fw in model.Frameworks)
            sb.AppendLine($"    \"-framework {fw}\"");

        // Path and git dependencies (linked by CMake target name)
        foreach (var dep in model.Dependencies)
        {
            if (dep.Value is ComplexDependency cd)
            {
                if (cd.Path is not null || cd.Git is not null)
                    sb.AppendLine($"    {EscapeName(dep.Name)}");
            }
        }

        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void WriteFetchContent(StringBuilder sb, FlatProjectModel model)
    {
        var gitDeps = model.Dependencies
            .Where(d => d.Value is ComplexDependency { Git: not null })
            .Select(d => (d.Name, (ComplexDependency)d.Value))
            .ToList();

        if (gitDeps.Count == 0) return;

        sb.AppendLine("include(FetchContent)");
        sb.AppendLine();

        foreach (var (name, cd) in gitDeps)
        {
            var tagOrCommit = cd.Tag ?? cd.Commit ?? "main";
            sb.AppendLine($"FetchContent_Declare({EscapeName(name)}");
            sb.AppendLine($"    GIT_REPOSITORY {cd.Git}");
            sb.AppendLine($"    GIT_TAG        {tagOrCommit}");
            sb.AppendLine($"    GIT_SHALLOW    TRUE");
            sb.AppendLine(")");
            sb.AppendLine($"FetchContent_MakeAvailable({EscapeName(name)})");
            sb.AppendLine();
        }
    }

    private static void WriteSubdirectories(StringBuilder sb, FlatProjectModel model)
    {
        var pathDeps = model.Dependencies
            .Where(d => d.Value is ComplexDependency { Path: not null })
            .Select(d => ((ComplexDependency)d.Value).Path!)
            .ToList();

        if (pathDeps.Count == 0) return;

        foreach (var path in pathDeps)
            sb.AppendLine($"add_subdirectory({path})");
        sb.AppendLine();
    }

    private static void WriteOutputDirectories(StringBuilder sb, FlatProjectModel model)
    {
        var output = model.Output!;
        var targetName = EscapeName(model.Name);

        sb.AppendLine($"set_target_properties({targetName} PROPERTIES");
        if (output.Binaries is not null)
        {
            sb.AppendLine($"    RUNTIME_OUTPUT_DIRECTORY \"{output.Binaries}\"");
            sb.AppendLine($"    LIBRARY_OUTPUT_DIRECTORY \"{output.Binaries}\"");
        }
        if (output.Libraries is not null)
            sb.AppendLine($"    ARCHIVE_OUTPUT_DIRECTORY \"{output.Libraries}\"");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void WriteCustomCommands(StringBuilder sb, FlatProjectModel model)
    {
        if (model.PreBuildCommands.Count > 0)
        {
            sb.AppendLine($"add_custom_command(TARGET {EscapeName(model.Name)} PRE_BUILD");
            foreach (var cmd in model.PreBuildCommands)
                sb.AppendLine($"    COMMAND {cmd}");
            sb.AppendLine(")");
            sb.AppendLine();
        }

        if (model.PostBuildCommands.Count > 0)
        {
            sb.AppendLine($"add_custom_command(TARGET {EscapeName(model.Name)} POST_BUILD");
            foreach (var cmd in model.PostBuildCommands)
                sb.AppendLine($"    COMMAND {cmd}");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }

    private static void WriteVersionDependencyHints(StringBuilder sb, FlatProjectModel model)
    {
        var versionDeps = model.Dependencies
            .Where(d => d.Value is VersionDependency || d.Value is ComplexDependency { Version: not null })
            .ToList();

        if (versionDeps.Count == 0) return;

        sb.AppendLine("# Version dependencies must be resolved manually or via a package manager:");
        foreach (var dep in versionDeps)
        {
            var ver = dep.Value switch
            {
                VersionDependency vd              => vd.Version,
                ComplexDependency { Version: var v } => v,
                _                                  => "unknown",
            };
            sb.AppendLine($"# find_package({EscapeName(dep.Name)} {ver} REQUIRED)");
        }
        sb.AppendLine();
    }

    private static List<string> ExpandGlobs(FlatProjectModel model)
    {
        var result = new List<string>();

        foreach (var item in model.Sources)
        {
            var pattern = item.Glob;
            var abs = Path.IsPathRooted(pattern)
                ? pattern
                : Path.Combine(model.ProjectDir, pattern);

            try
            {
                var files = Glob(abs);
                if (files.Count > 0)
                {
                    // Use relative paths from the project directory
                    foreach (var f in files)
                        result.Add(MakeRelative(model.ProjectDir, f));
                }
                else
                {
                    // Keep as glob pattern for CMake file(GLOB ...)
                    result.Add(pattern);
                }
            }
            catch
            {
                result.Add(pattern);
            }
        }

        return result;
    }

    private static List<string> Glob(string pattern)
    {
        var dir = Path.GetDirectoryName(pattern) ?? ".";
        var filePattern = Path.GetFileName(pattern);

        if (!Directory.Exists(dir)) return [];

        var searchOption = filePattern.StartsWith("**")
            ? SearchOption.AllDirectories
            : SearchOption.TopDirectoryOnly;

        var actualPattern = filePattern.TrimStart('*').TrimStart('/');
        if (string.IsNullOrEmpty(actualPattern)) actualPattern = "*";

        return Directory.GetFiles(dir, actualPattern, searchOption)
            .OrderBy(f => f)
            .ToList();
    }

    private static string MakeRelative(string baseDir, string path)
    {
        var rel = Path.GetRelativePath(baseDir, path);
        return rel.Replace('\\', '/');
    }

    private static string EscapeName(string name) =>
        name.Replace('-', '_').Replace(' ', '_');
}
