using System.Text;
using Dotori.Core.Model;
using Dotori.Core.Parsing;

namespace Dotori.Core.Generators;

/// <summary>
/// Generates a GNU Makefile from a flattened project model.
/// Generates a single Makefile with DEBUG/RELEASE variable-driven switching.
/// </summary>
public sealed class MakefileGenerator : IBuildSystemGenerator
{
    public string FormatId => "makefile";

    public IReadOnlyList<(string RelativePath, string Content)> Generate(
        FlatProjectModel model,
        string config,
        string targetId)
    {
        return [("Makefile", GenerateMakefile(model, config, targetId))];
    }

    private static string GenerateMakefile(FlatProjectModel model, string config, string targetId)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by dotori export build-system --format makefile");
        sb.AppendLine("# Do not edit manually — re-run the command to regenerate.");
        sb.AppendLine("# Usage: make [CONFIG=debug|release]");
        sb.AppendLine();

        // Default config
        var defaultConfig = config == "release" ? "release" : "debug";
        sb.AppendLine($"CONFIG ?= {defaultConfig}");
        sb.AppendLine();

        // Compiler
        var cxx = DetectCxx(targetId);
        var ar  = "ar";
        sb.AppendLine($"CXX = {cxx}");
        sb.AppendLine($"AR  = {ar}");
        sb.AppendLine();

        // C++ standard
        var stdFlag = model.Std switch
        {
            CxxStd.Cxx17 => "-std=c++17",
            CxxStd.Cxx20 => "-std=c++20",
            CxxStd.Cxx23 => "-std=c++23",
            _             => "-std=c++23",
        };

        // Base flags common to both configs
        var baseFlags = new List<string> { stdFlag };

        // Include dirs
        foreach (var h in model.Headers)
            baseFlags.Add($"-I{h.Path}");

        // Defines
        foreach (var def in model.Defines)
            baseFlags.Add($"-D{def}");

        baseFlags.AddRange(model.CompileFlags);

        // Warnings
        switch (model.Warnings)
        {
            case WarningLevel.None:    baseFlags.Add("-w"); break;
            case WarningLevel.All:     baseFlags.Add("-Wall"); break;
            case WarningLevel.Extra:   baseFlags.Add("-Wall"); baseFlags.Add("-Wextra"); break;
        }
        if (model.WarningsAsErrors) baseFlags.Add("-Werror");

        sb.AppendLine($"CXXFLAGS_BASE = {string.Join(" ", baseFlags)}");
        sb.AppendLine();

        // Debug flags
        var debugFlags = new List<string> { "-O0", "-g" };
        if (model.DebugInfo == DebugInfoLevel.None) debugFlags.Remove("-g");
        sb.AppendLine($"CXXFLAGS_DEBUG   = $(CXXFLAGS_BASE) {string.Join(" ", debugFlags)}");

        // Release flags
        var releaseFlags = new List<string>();
        var optFlag = model.Optimize switch
        {
            OptimizeLevel.Size  => "-Os",
            OptimizeLevel.Speed => "-O2",
            OptimizeLevel.Full  => "-O3",
            _                   => "-O2",
        };
        releaseFlags.Add(optFlag);
        if (model.DebugInfo != DebugInfoLevel.None)
            releaseFlags.Add(model.DebugInfo == DebugInfoLevel.Full ? "-g" : "-g1");
        if (model.Lto) releaseFlags.Add("-flto");
        sb.AppendLine($"CXXFLAGS_RELEASE = $(CXXFLAGS_BASE) {string.Join(" ", releaseFlags)}");
        sb.AppendLine();

        // Select config flags
        sb.AppendLine("ifeq ($(CONFIG),release)");
        sb.AppendLine("  CXXFLAGS = $(CXXFLAGS_RELEASE)");
        sb.AppendLine("  OBJDIR   = .dotori-make/release/obj");
        var relBin = model.Output?.Binaries ?? ".dotori-make/release/bin";
        sb.AppendLine($"  BINDIR   = {relBin}");
        sb.AppendLine("else");
        sb.AppendLine("  CXXFLAGS = $(CXXFLAGS_DEBUG)");
        sb.AppendLine("  OBJDIR   = .dotori-make/debug/obj");
        var dbgBin = model.Output?.Binaries ?? ".dotori-make/debug/bin";
        sb.AppendLine($"  BINDIR   = {dbgBin}");
        sb.AppendLine("endif");
        sb.AppendLine();

        // Link flags
        var ldFlags = new List<string>(model.LinkFlags);
        foreach (var lib in model.Links) ldFlags.Add($"-l{lib}");
        foreach (var fw in model.Frameworks) { ldFlags.Add("-framework"); ldFlags.Add(fw); }
        sb.AppendLine($"LDFLAGS = {string.Join(" ", ldFlags)}");
        sb.AppendLine();

        // Source files
        var sourceFiles = ExpandSourceFiles(model);
        if (sourceFiles.Count > 0)
        {
            sb.AppendLine("SRCS = \\");
            for (int i = 0; i < sourceFiles.Count; i++)
            {
                var rel = Path.GetRelativePath(model.ProjectDir, sourceFiles[i]).Replace('\\', '/');
                var cont = i < sourceFiles.Count - 1 ? " \\" : "";
                sb.AppendLine($"  {rel}{cont}");
            }
            sb.AppendLine();
            sb.AppendLine("OBJS = $(patsubst %,$(OBJDIR)/%.o,$(subst /,_,$(SRCS)))");
        }
        else
        {
            sb.AppendLine("SRCS =");
            sb.AppendLine("OBJS =");
        }
        sb.AppendLine();

        // Target name
        var outputName = GetOutputName(model, targetId);
        sb.AppendLine($"TARGET = $(BINDIR)/{outputName}");
        sb.AppendLine();

        // Default target
        sb.AppendLine(".PHONY: all clean");
        sb.AppendLine("all: $(TARGET)");
        sb.AppendLine();

        // Link rule
        if (model.Type == ProjectType.StaticLibrary)
        {
            sb.AppendLine("$(TARGET): $(OBJS) | $(BINDIR)");
            sb.AppendLine("\t$(AR) rcs $@ $^");
        }
        else
        {
            sb.AppendLine("$(TARGET): $(OBJS) | $(BINDIR)");
            sb.AppendLine("\t$(CXX) $(LDFLAGS) $^ -o $@");
        }
        sb.AppendLine();

        // Compile rule (generic pattern using mangled names)
        sb.AppendLine("$(OBJDIR)/%.o: | $(OBJDIR)");
        sb.AppendLine("\t$(CXX) $(CXXFLAGS) -MMD -MF $@.d -c $(patsubst $(OBJDIR)/%.o,%,$(subst _,/,$@)) -o $@");
        sb.AppendLine();

        // Directory creation
        sb.AppendLine("$(OBJDIR) $(BINDIR):");
        sb.AppendLine("\tmkdir -p $@");
        sb.AppendLine();

        // Include dependency files
        sb.AppendLine("-include $(OBJS:.o=.o.d)");
        sb.AppendLine();

        // Clean
        sb.AppendLine("clean:");
        sb.AppendLine("\trm -rf .dotori-make");

        // Dependency hints
        WriteDependencyHints(sb, model);

        return sb.ToString();
    }

    private static void WriteDependencyHints(StringBuilder sb, FlatProjectModel model)
    {
        var deps = model.Dependencies.Where(d =>
            d.Value is VersionDependency ||
            d.Value is ComplexDependency).ToList();

        if (deps.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("# External dependencies (resolve manually before building):");
        foreach (var dep in deps)
        {
            var info = dep.Value switch
            {
                VersionDependency vd                             => $"version {vd.Version}",
                ComplexDependency { Git: var g } when g is not null => $"git {g}",
                ComplexDependency { Path: var p } when p is not null => $"path {p}",
                _                                               => "",
            };
            sb.AppendLine($"# {dep.Name}: {info}");
        }
    }

    private static string GetOutputName(FlatProjectModel model, string targetId)
    {
        var name = SanitizeName(model.Name);
        var isWindows = targetId.StartsWith("windows");

        return model.Type switch
        {
            ProjectType.Executable    => isWindows ? $"{name}.exe" : name,
            ProjectType.StaticLibrary => $"lib{name}.a",
            ProjectType.SharedLibrary => isWindows ? $"{name}.dll"
                                       : targetId.Contains("macos") ? $"lib{name}.dylib"
                                       : $"lib{name}.so",
            _                         => name,
        };
    }

    private static string DetectCxx(string targetId) =>
        targetId.Contains("windows") && !targetId.Contains("clang") ? "cl" : "c++";

    private static string SanitizeName(string name) => name.Replace('-', '_').Replace(' ', '_');

    private static List<string> ExpandSourceFiles(FlatProjectModel model)
    {
        var result = new List<string>();
        foreach (var item in model.Sources)
        {
            var pattern = item.Glob;
            var abs = Path.IsPathRooted(pattern)
                ? pattern
                : Path.Combine(model.ProjectDir, pattern);

            try
            {
                var dir = Path.GetDirectoryName(abs) ?? ".";
                var filePattern = Path.GetFileName(abs);
                if (!Directory.Exists(dir)) { result.Add(abs); continue; }

                var search = filePattern.StartsWith("**")
                    ? SearchOption.AllDirectories
                    : SearchOption.TopDirectoryOnly;
                var pat = filePattern.TrimStart('*').TrimStart('/');
                if (string.IsNullOrEmpty(pat)) pat = "*";

                result.AddRange(Directory.GetFiles(dir, pat, search).OrderBy(f => f));
            }
            catch
            {
                result.Add(abs);
            }
        }
        return result;
    }
}
