using System.Text;
using Dotori.Core.Model;
using Dotori.Core.Parsing;

namespace Dotori.Core.Generators;

/// <summary>
/// Generates meson.build from a flattened project model.
/// Path dependencies are included via subproject() wraps.
/// Git and version dependencies are noted as comments.
/// </summary>
public sealed class MesonGenerator : IBuildSystemGenerator
{
    public string FormatId => "meson";

    public IReadOnlyList<(string RelativePath, string Content)> Generate(
        FlatProjectModel model,
        string config,
        string targetId)
    {
        var sb = new StringBuilder();
        WriteMesonBuild(sb, model, config);
        return [("meson.build", sb.ToString())];
    }

    private static void WriteMesonBuild(StringBuilder sb, FlatProjectModel model, string config)
    {
        sb.AppendLine("# Generated by dotori export build-system --format meson");
        sb.AppendLine("# Do not edit manually — re-run the command to regenerate.");
        sb.AppendLine();

        var stdStr = model.Std switch
        {
            CxxStd.Cxx17 => "c++17",
            CxxStd.Cxx20 => "c++20",
            CxxStd.Cxx23 => "c++23",
            _             => "c++23",
        };

        sb.AppendLine($"project('{model.Name}', 'cpp',");
        sb.AppendLine($"  default_options: ['cpp_std={stdStr}'])");
        sb.AppendLine();

        // Version dependency hints
        WriteVersionDependencyHints(sb, model);

        // Path dependencies via subproject
        WriteSubprojects(sb, model);

        // Compile args
        var cppArgs  = BuildCppArgs(model, config);
        var linkArgs = model.LinkFlags.ToList();

        // Include directories
        var inclDirs = model.Headers.Select(h => h.Path).Distinct().ToList();

        // Sources
        var sources = ExpandSources(model);

        // Target declaration
        WriteTarget(sb, model, sources, cppArgs, linkArgs, inclDirs);
    }

    private static void WriteTarget(
        StringBuilder sb,
        FlatProjectModel model,
        List<string> sources,
        List<string> cppArgs,
        List<string> linkArgs,
        List<string> inclDirs)
    {
        var name = QuoteStr(model.Name);

        if (model.Type == ProjectType.HeaderOnly)
        {
            sb.AppendLine($"{EscapeName(model.Name)}_dep = declare_dependency(");

            if (inclDirs.Count > 0)
            {
                sb.AppendLine($"  include_directories: include_directories(");
                for (int i = 0; i < inclDirs.Count; i++)
                {
                    var comma = i < inclDirs.Count - 1 ? "," : "";
                    sb.AppendLine($"    {QuoteStr(inclDirs[i])}{comma}");
                }
                sb.AppendLine("  ),");
            }

            sb.AppendLine(")");
            sb.AppendLine();
            return;
        }

        var funcName = model.Type switch
        {
            ProjectType.Executable    => "executable",
            ProjectType.StaticLibrary => "static_library",
            ProjectType.SharedLibrary => "shared_library",
            _                         => "executable",
        };

        sb.AppendLine($"{EscapeName(model.Name)} = {funcName}({name},");

        // Sources
        if (sources.Count > 0)
        {
            sb.AppendLine("  sources: files(");
            for (int i = 0; i < sources.Count; i++)
            {
                var comma = i < sources.Count - 1 ? "," : "";
                sb.AppendLine($"    {QuoteStr(sources[i])}{comma}");
            }
            sb.AppendLine("  ),");
        }

        // Include directories
        if (inclDirs.Count > 0)
        {
            sb.AppendLine("  include_directories: include_directories(");
            for (int i = 0; i < inclDirs.Count; i++)
            {
                var comma = i < inclDirs.Count - 1 ? "," : "";
                sb.AppendLine($"    {QuoteStr(inclDirs[i])}{comma}");
            }
            sb.AppendLine("  ),");
        }

        // cpp_args
        var allCppArgs = new List<string>(cppArgs);
        foreach (var def in model.Defines)
            allCppArgs.Add($"-D{def}");

        if (allCppArgs.Count > 0)
        {
            sb.AppendLine("  cpp_args: [");
            for (int i = 0; i < allCppArgs.Count; i++)
            {
                var comma = i < allCppArgs.Count - 1 ? "," : "";
                sb.AppendLine($"    {QuoteStr(allCppArgs[i])}{comma}");
            }
            sb.AppendLine("  ],");
        }

        // link_args
        if (linkArgs.Count > 0)
        {
            sb.AppendLine("  link_args: [");
            for (int i = 0; i < linkArgs.Count; i++)
            {
                var comma = i < linkArgs.Count - 1 ? "," : "";
                sb.AppendLine($"    {QuoteStr(linkArgs[i])}{comma}");
            }
            sb.AppendLine("  ],");
        }

        // dependencies (path deps linked by subproject)
        var pathDeps = model.Dependencies
            .Where(d => d.Value is ComplexDependency { Path: not null })
            .ToList();

        var allDeps = new List<string>();
        foreach (var dep in pathDeps)
            allDeps.Add($"{EscapeName(dep.Name)}_dep");

        // System link libs
        foreach (var lib in model.Links)
            allDeps.Add($"dependency('{lib}', required: false)");

        if (allDeps.Count > 0)
        {
            sb.AppendLine("  dependencies: [");
            for (int i = 0; i < allDeps.Count; i++)
            {
                var comma = i < allDeps.Count - 1 ? "," : "";
                sb.AppendLine($"    {allDeps[i]}{comma}");
            }
            sb.AppendLine("  ],");
        }

        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void WriteSubprojects(StringBuilder sb, FlatProjectModel model)
    {
        var pathDeps = model.Dependencies
            .Where(d => d.Value is ComplexDependency { Path: not null })
            .Select(d => (d.Name, ((ComplexDependency)d.Value).Path!))
            .ToList();

        if (pathDeps.Count == 0) return;

        foreach (var (name, path) in pathDeps)
        {
            sb.AppendLine($"{EscapeName(name)}_proj = subproject('{name}')");
            sb.AppendLine($"{EscapeName(name)}_dep = {EscapeName(name)}_proj.get_variable('{EscapeName(name)}_dep')");
        }
        sb.AppendLine();
    }

    private static void WriteVersionDependencyHints(StringBuilder sb, FlatProjectModel model)
    {
        var versionDeps = model.Dependencies
            .Where(d => d.Value is VersionDependency or ComplexDependency { Version: not null, Path: null, Git: null })
            .ToList();

        var gitDeps = model.Dependencies
            .Where(d => d.Value is ComplexDependency { Git: not null })
            .ToList();

        if (versionDeps.Count == 0 && gitDeps.Count == 0) return;

        if (versionDeps.Count > 0)
        {
            sb.AppendLine("# Version dependencies — install via package manager or provide wraps:");
            foreach (var dep in versionDeps)
            {
                var ver = dep.Value switch
                {
                    VersionDependency vd                   => vd.Version,
                    ComplexDependency { Version: var v }   => v ?? "unknown",
                    _                                      => "unknown",
                };
                sb.AppendLine($"# {EscapeName(dep.Name)}_dep = dependency('{dep.Name}', version: '>={ver}')");
            }
            sb.AppendLine();
        }

        if (gitDeps.Count > 0)
        {
            sb.AppendLine("# Git dependencies — add as Meson wraps in subprojects/:");
            foreach (var dep in gitDeps)
            {
                var cd = (ComplexDependency)dep.Value;
                sb.AppendLine($"# {dep.Name}: {cd.Git} @ {cd.Tag ?? cd.Commit ?? "main"}");
            }
            sb.AppendLine();
        }
    }

    private static List<string> BuildCppArgs(FlatProjectModel model, string config)
    {
        var args = new List<string>(model.CompileFlags);

        // Optimization
        var optFlag = model.Optimize switch
        {
            OptimizeLevel.Size  => "-Os",
            OptimizeLevel.Speed => "-O2",
            OptimizeLevel.Full  => "-O3",
            _                   => null,
        };
        if (optFlag is not null) args.Add(optFlag);

        // Debug info
        if (model.DebugInfo != DebugInfoLevel.None)
            args.Add(model.DebugInfo == DebugInfoLevel.Full ? "-g" : "-g1");

        // Warnings
        switch (model.Warnings)
        {
            case WarningLevel.None:    args.Add("-w");    break;
            case WarningLevel.All:     args.Add("-Wall"); break;
            case WarningLevel.Extra:   args.Add("-Wall"); args.Add("-Wextra"); break;
        }
        if (model.WarningsAsErrors) args.Add("-Werror");

        return args;
    }

    private static List<string> ExpandSources(FlatProjectModel model)
    {
        var result = new List<string>();
        foreach (var item in model.Sources)
        {
            var pattern = item.Glob;
            var abs = Path.IsPathRooted(pattern)
                ? pattern
                : Path.Combine(model.ProjectDir, pattern);

            try
            {
                var files = GlobFiles(abs);
                if (files.Count > 0)
                {
                    foreach (var f in files)
                        result.Add(Path.GetRelativePath(model.ProjectDir, f).Replace('\\', '/'));
                }
                else
                {
                    result.Add(pattern);
                }
            }
            catch
            {
                result.Add(pattern);
            }
        }
        return result;
    }

    private static List<string> GlobFiles(string pattern)
    {
        var dir = Path.GetDirectoryName(pattern) ?? ".";
        var filePattern = Path.GetFileName(pattern);
        if (!Directory.Exists(dir)) return [];

        var searchOption = filePattern.StartsWith("**")
            ? SearchOption.AllDirectories
            : SearchOption.TopDirectoryOnly;

        var actualPattern = filePattern.TrimStart('*').TrimStart('/');
        if (string.IsNullOrEmpty(actualPattern)) actualPattern = "*";

        return Directory.GetFiles(dir, actualPattern, searchOption)
            .OrderBy(f => f).ToList();
    }

    private static string EscapeName(string name) => name.Replace('-', '_').Replace(' ', '_');
    private static string QuoteStr(string s) => $"'{s}'";
}
