using System.Text;
using Dotori.Core.Model;
using Dotori.Core.Parsing;

namespace Dotori.Core.Generators;

/// <summary>
/// Generates a build.ninja file from a flattened project model.
/// Generates one file per config when config == "both".
/// </summary>
public sealed class NinjaGenerator : IBuildSystemGenerator
{
    public string FormatId => "ninja";

    public IReadOnlyList<(string RelativePath, string Content)> Generate(
        FlatProjectModel model,
        string config,
        string targetId)
    {
        if (config == "both")
        {
            return
            [
                ("build.debug.ninja",   GenerateNinja(model, "debug",   targetId)),
                ("build.release.ninja", GenerateNinja(model, "release", targetId)),
            ];
        }

        return [("build.ninja", GenerateNinja(model, config, targetId))];
    }

    private static string GenerateNinja(FlatProjectModel model, string config, string targetId)
    {
        var sb = new StringBuilder();
        var isDebug = config == "debug";

        sb.AppendLine($"# Generated by dotori export build-system --format ninja ({config})");
        sb.AppendLine("# Do not edit manually — re-run the command to regenerate.");
        sb.AppendLine();

        // Variables
        var cxx = DetectCxx(targetId);
        sb.AppendLine($"cxx = {cxx}");
        sb.AppendLine($"ar  = ar");
        sb.AppendLine();

        var cxxflags = BuildCxxFlags(model, isDebug);
        var ldflags  = BuildLdFlags(model);

        sb.AppendLine($"cxxflags = {cxxflags}");
        sb.AppendLine($"ldflags  = {ldflags}");
        sb.AppendLine();

        // Rules
        sb.AppendLine("rule cxx");
        sb.AppendLine("  command = $cxx $cxxflags -MMD -MF $out.d -c $in -o $out");
        sb.AppendLine("  depfile = $out.d");
        sb.AppendLine("  deps    = gcc");
        sb.AppendLine("  description = CXX $out");
        sb.AppendLine();

        if (model.Type == ProjectType.StaticLibrary)
        {
            sb.AppendLine("rule ar");
            sb.AppendLine("  command = $ar rcs $out $in");
            sb.AppendLine("  description = AR $out");
        }
        else
        {
            sb.AppendLine("rule link");
            sb.AppendLine("  command = $cxx $ldflags $in -o $out");
            sb.AppendLine("  description = LINK $out");
        }
        sb.AppendLine();

        // Build statements
        var sourceFiles = ExpandSourceFiles(model);
        var objDir = $".dotori-ninja/{config}/obj";
        var binDir = model.Output?.Binaries ?? $".dotori-ninja/{config}/bin";

        var objFiles = new List<string>();
        foreach (var src in sourceFiles)
        {
            var rel = Path.GetRelativePath(model.ProjectDir, src).Replace('\\', '/');
            var obj = $"{objDir}/{rel.Replace('/', '_').Replace(' ', '_')}.o";
            objFiles.Add(obj);
            sb.AppendLine($"build {obj}: cxx {rel}");
        }
        sb.AppendLine();

        // Link/archive
        var targetOutput = GetOutputName(model, binDir, targetId);
        var ruleToUse = model.Type == ProjectType.StaticLibrary ? "ar" : "link";

        if (objFiles.Count > 0)
        {
            sb.AppendLine($"build {targetOutput}: {ruleToUse} {string.Join(" ", objFiles)}");
            sb.AppendLine();
        }

        sb.AppendLine($"default {targetOutput}");
        sb.AppendLine();

        // Dependency hints
        WriteDependencyHints(sb, model);

        return sb.ToString();
    }

    private static void WriteDependencyHints(StringBuilder sb, FlatProjectModel model)
    {
        var deps = model.Dependencies.Where(d =>
            d.Value is VersionDependency ||
            d.Value is ComplexDependency { Git: not null }).ToList();

        if (deps.Count == 0) return;

        sb.AppendLine("# Dependencies must be resolved before building:");
        foreach (var dep in deps)
        {
            var info = dep.Value switch
            {
                VersionDependency vd => $"version {vd.Version}",
                ComplexDependency cd => $"git {cd.Git} @ {cd.Tag ?? cd.Commit ?? "main"}",
                _                    => "",
            };
            sb.AppendLine($"# {dep.Name}: {info}");
        }
    }

    private static string BuildCxxFlags(FlatProjectModel model, bool isDebug)
    {
        var flags = new List<string>();

        // C++ standard
        var stdFlag = model.Std switch
        {
            CxxStd.Cxx17 => "-std=c++17",
            CxxStd.Cxx20 => "-std=c++20",
            CxxStd.Cxx23 => "-std=c++23",
            _             => "-std=c++23",
        };
        flags.Add(stdFlag);

        // Optimization
        if (!isDebug)
        {
            var optFlag = model.Optimize switch
            {
                OptimizeLevel.Size  => "-Os",
                OptimizeLevel.Speed => "-O2",
                OptimizeLevel.Full  => "-O3",
                _                   => null,
            };
            if (optFlag is not null) flags.Add(optFlag);
        }
        else
        {
            flags.Add("-O0");
        }

        // Debug info
        if (model.DebugInfo != DebugInfoLevel.None || isDebug)
            flags.Add(model.DebugInfo == DebugInfoLevel.Full || isDebug ? "-g" : "-g1");

        // Warnings
        switch (model.Warnings)
        {
            case WarningLevel.None:    flags.Add("-w"); break;
            case WarningLevel.All:     flags.Add("-Wall"); break;
            case WarningLevel.Extra:   flags.Add("-Wall"); flags.Add("-Wextra"); break;
        }
        if (model.WarningsAsErrors) flags.Add("-Werror");

        // Include directories
        foreach (var h in model.Headers)
            flags.Add($"-I{h.Path}");

        // Defines
        foreach (var def in model.Defines)
            flags.Add($"-D{def}");

        // Additional compile flags
        flags.AddRange(model.CompileFlags);

        return string.Join(" ", flags);
    }

    private static string BuildLdFlags(FlatProjectModel model)
    {
        var flags = new List<string>(model.LinkFlags);

        foreach (var lib in model.Links)
            flags.Add($"-l{lib}");

        foreach (var fw in model.Frameworks)
        {
            flags.Add("-framework");
            flags.Add(fw);
        }

        if (model.Lto) flags.Add("-flto");

        return string.Join(" ", flags);
    }

    private static string GetOutputName(FlatProjectModel model, string binDir, string targetId)
    {
        var name = SanitizeName(model.Name);
        var isWindows = targetId.StartsWith("windows");

        return model.Type switch
        {
            ProjectType.Executable    => isWindows ? $"{binDir}/{name}.exe" : $"{binDir}/{name}",
            ProjectType.StaticLibrary => $"{binDir}/lib{name}.a",
            ProjectType.SharedLibrary => isWindows ? $"{binDir}/{name}.dll"
                                       : targetId.Contains("macos") ? $"{binDir}/lib{name}.dylib"
                                       : $"{binDir}/lib{name}.so",
            ProjectType.HeaderOnly    => $"{binDir}/{name}.phony",
            _                         => $"{binDir}/{name}",
        };
    }

    private static string DetectCxx(string targetId) =>
        targetId.Contains("windows") && !targetId.Contains("clang") ? "cl" : "c++";

    private static string SanitizeName(string name) => name.Replace('-', '_').Replace(' ', '_');

    private static List<string> ExpandSourceFiles(FlatProjectModel model)
    {
        var result = new List<string>();
        foreach (var item in model.Sources)
        {
            var pattern = item.Glob;
            var abs = Path.IsPathRooted(pattern)
                ? pattern
                : Path.Combine(model.ProjectDir, pattern);

            try
            {
                var dir = Path.GetDirectoryName(abs) ?? ".";
                var filePattern = Path.GetFileName(abs);
                if (!Directory.Exists(dir)) { result.Add(abs); continue; }

                var search = filePattern.StartsWith("**")
                    ? SearchOption.AllDirectories
                    : SearchOption.TopDirectoryOnly;
                var pat = filePattern.TrimStart('*').TrimStart('/');
                if (string.IsNullOrEmpty(pat)) pat = "*";

                result.AddRange(Directory.GetFiles(dir, pat, search).OrderBy(f => f));
            }
            catch
            {
                result.Add(abs);
            }
        }
        return result;
    }
}
